version: '3.5'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.2.4
    container_name: zookeeperx
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181 
    networks:
      clickhouse-network:
        ipv4_address: 172.24.0.10       
  kafka1:
    image: confluentinc/cp-kafka:5.3.1
    depends_on:
      - zookeeper
    ports:
      - "127.0.0.1:9092:9092"
      - "127.0.0.1:9998:9998"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      JMX_PORT: 9998
      KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka1 -Dcom.sun.management.jmxremote.rmi.port=9998      
    networks:
      clickhouse-network:
  schemaregistry1:
    image: confluentinc/cp-schema-registry:5.5.0
    ports:
      - 18085:8085
    depends_on:
      - zookeeper
      - kafka1
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka1:29092
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper1:2181
      SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: PLAINTEXT
      SCHEMA_REGISTRY_HOST_NAME: schemaregistry1
      SCHEMA_REGISTRY_LISTENERS: http://schemaregistry1:8085

      SCHEMA_REGISTRY_SCHEMA_REGISTRY_INTER_INSTANCE_PROTOCOL: "http"
      SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL: INFO
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC: _schemas
    networks:
      clickhouse-network:
  kafka-ui:
    container_name: kafka-ui-rx
    image: provectuslabs/kafka-ui:latest
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - zookeeper
      - kafka1
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka1:29092
    networks:
      clickhouse-network:
  clickhouse01:
    image: clickhouse/clickhouse-server:22.11
    container_name: clickhouse01
    hostname: clickhouse01
    networks:
      clickhouse-network:
        ipv4_address: 172.24.0.11
    ports:
      - "127.0.0.1:8123:8123"
      - "127.0.0.1:9000:9000"
    volumes:
      - ${PWD}/clickhouse01:/etc/clickhouse-server
    depends_on:
      - zookeeper
  clickhouse02:
    image: clickhouse/clickhouse-server:22.11
    container_name: clickhouse02
    hostname: clickhouse02
    networks:
      clickhouse-network:
        ipv4_address: 172.24.0.12
    volumes:
      - ${PWD}/clickhouse02:/etc/clickhouse-server
    depends_on:
      - zookeeper
  clickhouse03:
    image: clickhouse/clickhouse-server:22.11
    container_name: clickhouse03
    hostname: clickhouse03
    networks:
      clickhouse-network:
        ipv4_address: 172.24.0.13
    volumes:
      - ${PWD}/clickhouse03:/etc/clickhouse-server
    depends_on:
      - zookeeper
  clickhouse04:
    image: clickhouse/clickhouse-server:22.11
    container_name: clickhouse04
    hostname: clickhouse04
    networks:
      clickhouse-network:
        ipv4_address: 172.24.0.14
    volumes:
      - ${PWD}/clickhouse04:/etc/clickhouse-server
    depends_on:
      - zookeeper

networks:
  clickhouse-network:
    name: clickhouse-network
    ipam:
      config:
        - subnet: 172.24.0.0/24
